import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Context AI Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const year = new Date().getFullYear();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>        
        {/* Global Background */}
        <div className="fixed inset-0 -z-10">
          {/* Brightened layered gradient + radial accents */}
          <div className="absolute inset-0 bg-gradient-to-br from-[#0d1824] via-[#12304c] to-[#0b3a63]" />
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_25%_35%,rgba(99,167,255,0.40),transparent_60%)]" />
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_70%,rgba(56,189,248,0.28),transparent_65%)]" />
        </div>
        {/* Navbar */}
        <div className="fixed top-0 left-0 w-full z-50 px-4 md:px-8">
          <Navbar />
        </div>
        {/* Spacer for fixed navbar height */}
        <div className="pt-28 pb-12 px-4 md:px-8">
          {children}
          {/* Global Footer */}
          <footer className="w-full text-center py-10 border-t border-white/10 text-gray-300 text-sm mt-12">
            <div className="space-y-2">
              <p>
                <a href="mailto:crbarbaccia@crimson.ua.edu" className="hover:text-white underline underline-offset-4 decoration-white/30 hover:decoration-white">crbarbaccia@crimson.ua.edu</a>
              </p>
              <p className="text-gray-400">cr</p>
              <p>
                <a href="mailto:crkulawiak@crimson.ua.edu" className="hover:text-white underline underline-offset-4 decoration-white/30 hover:decoration-white">crkulawiak@crimson.ua.edu</a>
              </p>
              <p className="text-gray-400">© {year} <span className="text-white font-semibold">Contech</span>. All rights reserved.</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
